// Cedarwings SAS — Purchase Order generation + supplier email.
// Shared by inventory.html (requisition queue) and requisition.html.
//
//   import { createAndEmailPOs } from './po.js'
//   const res = await createAndEmailPOs(sb, items, {source, source_ref, createdBy})
//
// items: [{ item_name, quantity, unit?, unit_cost?, bom_id?, ref_id? }]
// Groups items by each item's preferred supplier, writes one purchase_orders
// row (+ purchase_order_lines) per supplier, emails the PO to the supplier,
// and returns a summary the caller can use to update the source rows.

import { CW_Notify } from './brevo.js'

function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}

// Default CC for every PO email, set in Settings (key: po_cc_email).
// Supports several addresses separated by comma/semicolon.
async function orderCc(sb){
  const { data } = await sb.from('system_settings').select('value').eq('key','po_cc_email').maybeSingle()
  const raw = (data && data.value) || ''
  const list = raw.split(/[,;]/).map(x=>x.trim()).filter(x=>x.includes('@'))
  return list.length ? list.map(email=>({email})) : null
}

function poHtml(po, supplier, lines, totalCost, currency){
  const rows = lines.map(l=>`<tr>
    <td style="padding:8px 10px;border-bottom:1px solid #eee">${esc(l.item_name)}</td>
    <td style="padding:8px 10px;border-bottom:1px solid #eee;text-align:right;font-family:monospace">${num(l.quantity).toLocaleString()}</td>
    <td style="padding:8px 10px;border-bottom:1px solid #eee">${esc(l.unit||'')}</td>
    <td style="padding:8px 10px;border-bottom:1px solid #eee;text-align:right;font-family:monospace">${num(l.unit_cost)?num(l.unit_cost).toLocaleString():'—'}</td>
    <td style="padding:8px 10px;border-bottom:1px solid #eee;text-align:right;font-family:monospace">${num(l.line_total)?num(l.line_total).toLocaleString():'—'}</td>
  </tr>`).join('')
  const cur = currency || ''
  return `<div style="font-family:Arial,Helvetica,sans-serif;max-width:640px;margin:auto;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden">
    <div style="background:#1e3a8a;color:#fff;padding:22px 26px">
      <div style="font-size:13px;letter-spacing:.5px;opacity:.85">PURCHASE ORDER</div>
      <div style="font-size:24px;font-weight:800;margin-top:2px">${esc(po.po_number)}</div>
    </div>
    <div style="padding:22px 26px;color:#111">
      <p style="margin:0 0 4px">Dear <strong>${esc(supplier.name)}</strong>,</p>
      <p style="margin:0 0 16px;color:#444">Please find our purchase order below. Kindly confirm availability and expected delivery date.</p>
      <table style="width:100%;border-collapse:collapse;font-size:13px">
        <thead><tr style="background:#f3f4f6;text-align:left">
          <th style="padding:8px 10px">Item</th>
          <th style="padding:8px 10px;text-align:right">Qty</th>
          <th style="padding:8px 10px">Unit</th>
          <th style="padding:8px 10px;text-align:right">Unit Cost</th>
          <th style="padding:8px 10px;text-align:right">Total</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <div style="text-align:right;margin-top:14px;font-size:15px;font-weight:800">
        Estimated total: ${num(totalCost)?num(totalCost).toLocaleString():'—'} ${esc(cur)}
      </div>
      <p style="margin:20px 0 0;font-size:12px;color:#777">Generated by Cedarwings SAS inventory system on ${new Date().toLocaleDateString('en-GB')}. This is an automated purchase order.</p>
    </div>
  </div>`
}

// Clone a past PO into a new one for the same supplier and email it.
export async function reorderPO(sb, poId, opts = {}){
  const { data: src } = await sb.from('purchase_orders').select('*').eq('id', poId).single()
  if (!src) return { ok:false, error:'PO not found' }
  const { data: lines } = await sb.from('purchase_order_lines').select('*').eq('po_id', poId)
  if (!lines || !lines.length) return { ok:false, error:'PO has no lines' }
  const totalCost = lines.reduce((a,l)=> a + num(l.line_total), 0)
  const { data: po, error: pe } = await sb.from('purchase_orders').insert({
    supplier_id: src.supplier_id, supplier_name: src.supplier_name, supplier_email: src.supplier_email,
    status: 'sent', source: 'reorder', source_ref: src.id,
    item_count: lines.length, total_cost: totalCost, currency: src.currency,
    created_by: opts.createdBy || null
  }).select().single()
  if (pe) return { ok:false, error: pe.message }
  await sb.from('purchase_order_lines').insert(lines.map(l => ({
    po_id: po.id, item_name: l.item_name, quantity: num(l.quantity),
    unit: l.unit, unit_cost: num(l.unit_cost), line_total: num(l.line_total), bom_id: l.bom_id
  })))
  let emailStatus = 'no_email'
  if (src.supplier_email){
    const sup = { name: src.supplier_name, currency: src.currency }
    const att = await poPdf(po, sup, lines, totalCost, src.currency)
    const r = await CW_Notify.sendEmail(src.supplier_email, src.supplier_name, `Purchase Order ${po.po_number}`,
      poHtml(po, sup, lines, totalCost, src.currency), 'purchase_order', att, await orderCc(sb))
    emailStatus = r.ok ? 'sent' : 'failed'
  }
  await sb.from('purchase_orders').update({
    emailed_at: src.supplier_email ? new Date().toISOString() : null, email_status: emailStatus
  }).eq('id', po.id)
  return { ok:true, po_number: po.po_number, emailStatus }
}

// Re-email an already-created PO to its supplier.
export async function resendPO(sb, poId){
  const { data: po } = await sb.from('purchase_orders').select('*').eq('id', poId).single()
  if (!po) return { ok:false, error:'PO not found' }
  const email = po.supplier_email
  if (!email) return { ok:false, error:'no email on file for supplier' }
  const { data: lines } = await sb.from('purchase_order_lines').select('*').eq('po_id', poId)
  const sup = { name: po.supplier_name, currency: po.currency }
  const att = await poPdf(po, sup, lines||[], po.total_cost, po.currency)
  const r = await CW_Notify.sendEmail(email, po.supplier_name, `Purchase Order ${po.po_number}`,
    poHtml(po, sup, lines||[], po.total_cost, po.currency), 'purchase_order', att, await orderCc(sb))
  await sb.from('purchase_orders').update({
    emailed_at: r.ok ? new Date().toISOString() : po.emailed_at,
    email_status: r.ok ? 'sent' : 'failed'
  }).eq('id', poId)
  return { ok: r.ok, error: r.error }
}

// Build a printable PDF for a PO and return a Brevo attachment array
// ([{content:<base64>, name:<file>}]) — or null if generation fails.
async function poPdf(po, supplier, lines, totalCost, currency){
  try{
    const { jsPDF } = await import('https://esm.sh/jspdf@2.5.1')
    const doc = new jsPDF({ unit:'pt', format:'a4' })
    const W = doc.internal.pageSize.getWidth()
    doc.setFillColor(30,58,138); doc.rect(0,0,W,70,'F')
    doc.setTextColor(255); doc.setFontSize(11); doc.text('PURCHASE ORDER', 40, 30)
    doc.setFontSize(20); doc.setFont(undefined,'bold'); doc.text(String(po.po_number||''), 40, 54)
    doc.setTextColor(20); doc.setFont(undefined,'normal'); doc.setFontSize(11)
    let y = 100
    doc.text(`Supplier: ${supplier.name||'—'}`, 40, y); y+=16
    doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`, 40, y); y+=24
    // header row
    doc.setFont(undefined,'bold'); doc.setFontSize(10)
    doc.text('Item',40,y); doc.text('Qty',300,y,{align:'right'}); doc.text('Unit',330,y)
    doc.text('Unit Cost',460,y,{align:'right'}); doc.text('Total',540,y,{align:'right'})
    y+=6; doc.setDrawColor(200); doc.line(40,y,W-40,y); y+=16
    doc.setFont(undefined,'normal')
    for(const l of lines){
      if(y>780){ doc.addPage(); y=60 }
      doc.text(String(l.item_name||'').slice(0,40),40,y)
      doc.text(num(l.quantity).toLocaleString(),300,y,{align:'right'})
      doc.text(String(l.unit||''),330,y)
      doc.text(num(l.unit_cost)?num(l.unit_cost).toLocaleString():'—',460,y,{align:'right'})
      doc.text(num(l.line_total)?num(l.line_total).toLocaleString():'—',540,y,{align:'right'})
      y+=18
    }
    y+=6; doc.line(40,y,W-40,y); y+=20
    doc.setFont(undefined,'bold'); doc.setFontSize(12)
    doc.text(`Estimated total: ${num(totalCost).toLocaleString()} ${currency||''}`, W-40, y, {align:'right'})
    const b64 = doc.output('datauristring').split(',')[1]
    return [{ content: b64, name: `${po.po_number||'purchase-order'}.pdf` }]
  }catch(e){ console.warn('[PO] PDF generation failed:', e.message); return null }
}

export async function createAndEmailPOs(sb, items, opts = {}){
  const clean = (items||[]).filter(i => i && i.item_name && num(i.quantity) > 0)
  const result = { pos: [], emailed: 0, failed: [], noSupplier: [] }
  if (!clean.length) return result

  // Resolve item -> preferred supplier, cost and unit.
  const { data: invItems } = await sb.from('inventory_items')
    .select('item_name,name,preferred_supplier_id,supplier_id,supplier_name,cost_per_unit,unit_cost,unit_of_measure,unit')
  const itemMap = {}
  ;(invItems||[]).forEach(it => {
    const nm = (it.item_name || it.name || '').trim().toLowerCase()
    if (nm && !itemMap[nm]) itemMap[nm] = it
  })
  const { data: suppliers } = await sb.from('suppliers').select('id,name,email,contact_email,currency')
  const supMap = {}; (suppliers||[]).forEach(s => { supMap[s.id] = s })
  const cc = await orderCc(sb)

  // Group by resolved supplier id.
  const groups = {}
  for (const i of clean){
    const it = itemMap[i.item_name.trim().toLowerCase()] || {}
    const supId = it.preferred_supplier_id || it.supplier_id || null
    const unitCost = i.unit_cost != null ? num(i.unit_cost)
                   : (num(it.cost_per_unit) || num(it.unit_cost) || 0)
    const unit = i.unit || it.unit_of_measure || it.unit || ''
    const line = { ...i, unit, unit_cost: unitCost, line_total: num(i.quantity) * unitCost }
    if (!supId || !supMap[supId]) { result.noSupplier.push(i.item_name); continue }
    ;(groups[supId] = groups[supId] || []).push(line)
  }
  result.noSupplier = [...new Set(result.noSupplier)]

  for (const [supId, lines] of Object.entries(groups)){
    const sup = supMap[supId]
    const email = sup.email || sup.contact_email || null
    const totalCost = lines.reduce((a,l)=> a + num(l.line_total), 0)
    const { data: po, error: pe } = await sb.from('purchase_orders').insert({
      supplier_id: sup.id, supplier_name: sup.name, supplier_email: email,
      status: 'sent', source: opts.source || null, source_ref: opts.source_ref || null,
      item_count: lines.length, total_cost: totalCost, currency: sup.currency || null,
      created_by: opts.createdBy || null
    }).select().single()
    if (pe){ result.failed.push(`${sup.name}: ${pe.message}`); continue }

    const { error: le } = await sb.from('purchase_order_lines').insert(lines.map(l => ({
      po_id: po.id, item_name: l.item_name, quantity: num(l.quantity),
      unit: l.unit || null, unit_cost: num(l.unit_cost), line_total: num(l.line_total),
      bom_id: l.bom_id || null
    })))
    if (le){ result.failed.push(`${sup.name}: lines ${le.message}`) }

    let emailStatus = 'no_email'
    if (email){
      const att = await poPdf(po, sup, lines, totalCost, sup.currency)
      const r = await CW_Notify.sendEmail(email, sup.name, `Purchase Order ${po.po_number}`, poHtml(po, sup, lines, totalCost, sup.currency), 'purchase_order', att, cc)
      emailStatus = r.ok ? 'sent' : 'failed'
      if (r.ok) result.emailed++; else result.failed.push(`${sup.name}: email ${r.error || 'failed'}`)
    } else {
      result.failed.push(`${sup.name}: no email on file`)
    }
    await sb.from('purchase_orders').update({
      emailed_at: email ? new Date().toISOString() : null, email_status: emailStatus
    }).eq('id', po.id)

    result.pos.push({
      id: po.id, po_number: po.po_number, supplier: sup.name,
      email, emailStatus, refIds: lines.map(l => l.ref_id).filter(Boolean)
    })
  }
  return result
}
